### ISSUE TITLE
HOQ DO I USE THIS MODEL FOR SLAM AND NAVIGATION?

### ISSUE THREAD

**Issue by PhilipAmadasun** [arjunskumar/turtlebot2_rplidar#1]
Hello, I'm not quite sure what else I should install, or what original turtlebot2 files I should edit so I can use the rplidar for SLAM and navigation? Would you know?

**Comment by arjunskumar** [comment]
@PhilipAmadasun This package is meant for simulation, if you have an access to rplidar hardware, please refer https://github.com/NickL77/RPLidar_Hector_SLAM

**Comment by PhilipAmadasun** [comment]
yes I am talking about doing SLAM in a simulation
